const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 12.5,
    img: "/images/item-1.jpeg",
    desc: "Fluffier than a cloud on a pogo stick, these buttermilk pancakes dance with butter and twirl in warm maple syrup!",
  },
  {
    id: 2,
    title: "Billy's buffalo burger",
    category: "lunch",
    price: 16.75,
    img: "/images/item-2.jpeg",
    desc: "A wild buffalo patty lassoed with cheddar, crispy onions, and a sassy sauce, galloping onto a toasted bun.",
  },
  {
    id: 3,
    title: "pink godzilla milkshake",
    category: "shakes",
    price: 8.99,
    img: "/images/item-3.jpeg",
    desc: "A roaring strawberry beast blended with vanilla ice cream, topped with a cookie, glazed doughnut, and whipped cream with a cherry crown!",
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 10.25,
    img: "/images/item-4.jpeg",
    desc: "Eggs on toast with beans so smoky they whistle a tune, lounging atop toast thicker than a farmer’s tallest tale!",
  },
  {
    id: 5,
    title: "Roethlis-burger",
    category: "lunch",
    price: 18.99,
    img: "/images/item-5.jpeg",
    desc: "A beefy quarterback of a burger, blitzing your taste buds with Swiss, tomato, arugula, and an egg on top, snapping a garlic aioli spiral right into Steelers’ victory territory!",
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 9.5,
    img: "/images/item-6.jpeg",
    desc: "Oreos tumble into a creamy whirlpool of chocolate and vanilla, sprinkled with cookie stardust!",
  },
  {
    id: 7,
    title: "bacon biscuit bites",
    category: "breakfast",
    price: 7.99,
    img: "/images/item-7.jpeg",
    desc: "Biscuits so flaky they giggle, pitted with bacon, egg, american cheese, and lettuce and served with honey butter that’s pure mischief!",
  },
  {
    id: 8,
    title: "american classic burger",
    category: "lunch",
    price: 14.25,
    img: "/images/item-8.jpeg",
    desc: "A burger patriot saluting with lettuce, tomato, and cheese, waving a mayo flag on a bun of glory!",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 11.99,
    img: "/images/item-9.jpeg",
    desc: "A swirly vanilla-choco duo with two straws, plotting a sweet escape under a sprinkle-and-caramel sky!",
  },
  {
    id: 10,
    title: "Sir Spudnick's Galactic Steak",
    category: "lunch",
    price: 22.5,
    img: "/images/item-10.jpeg",
    desc: "A 6oz steak zooming through space, orbiting a potato moon with sour cream craters and chive comets!",
  },
]
export default menu
